config/routes.rb
Kurotrade::Application.routes.draw do

  root :to => 'static_pages#index'

  #resource :session, :only => [:new, :create, :destroy]

  get "login" => 'sessions#new', as: :login
  post "session" => 'sessions#create' 
  get "logout" => 'sessions#destroy', as: :logout

  #get '/balances', :to => 'static_pages#balance_exp'
  match '/boarding/welcome', :to => 'static_pages#welcome', as: :welcome
  match '/boarding/partner', :to => 'static_pages#new_partner', as: :boarding_partner
  match '/boarding/individual', :to => 'static_pages#new_individual', as: :boarding_individual

  get '/dashboard', :to => 'static_pages#mock_dashboard', as: :dashboard
  get '/about', :to => 'static_pages#about', as: :about
  get '/contact', :to => 'static_pages#contact', as: :contact

  resources :transactions, :to => 'static_pages#index'
  match '/transactions/file_upload', :to => 'transactions#scottrade_csv_parser', :as => 'transactions_upload'

  resources :portfolios, :to => 'static_pages#index'

  resources :groups, :to => 'static_pages#index'
  match '/individual/new', :to => 'groups#new', :as => 'new_individual'

  resources :beta_users

  match '/users/new', :to => 'beta_users#new', :as => 'new_user'
  match '/beta', :to => 'beta_users#new', :as => 'new_user'
  get '/thanks', :to => 'static_pages#thanks', as: :thanks
  get '/features', :to => 'static_pages#features', as: :features
  resources :users
  
end

app/controllers/static_pages_controller.rb
require 'csv'
require 'date'
require 'open-uri'

class StaticPagesController < ApplicationController

	def index
	end

	# def balance_exp
	# 	@transactions_initial = Transaction.order(:trade_date)
	# 	@transactions = @transactions_initial.where(:user_id => 1)
	# end

  def mock_dashboard

    transactions = Transaction.where(:group_id => 1)
    transactions = transactions.order(:trade_date)

    # transactions_initial = Transaction.order(:trade_date)
    # transactions = transactions_initial.where(:group_id => 1)


    #if Time.now >= (Date.today.to_time+65000) 
      # collect tickers into array
      tickers = []
      tickers_list = transactions.pluck(:stock_symbol).uniq
      tickers_list.each do |ticker|
        if ticker != 'Cash'
        tickers << ticker
        end
      end

      puts tickers

      ### Mechanize Populate DB ###################################
      market_data = MarketData.all
      agent = Mechanize.new

      tickers.each do |symbol|
        page = agent.get("http://finance.yahoo.com/q/hp?s=#{symbol}+Historical+Prices")
        dl_csv = page.link_with(:text => 'Download to Spreadsheet').href
        puts dl_csv
        #puts "Begin: #{symbol}"
        # check if the ticker exists in the DB
        CSV.new(open(dl_csv), :headers => :first_row).each_with_index do |row, idx|
          if market_data.any? {|m| m[:ticker] == symbol}
            last_market_date = market_data.select {|m| m[:ticker] == symbol}.first
            if last_market_date[:market_date] < Date.parse(row.to_hash['Date'])
              add_market_data = MarketData.new
              add_market_data.update_attributes(
                :market_date => row.to_hash['Date'],
                :ticker => symbol,
                :close_price => row.to_hash['Close'],
                :adj_close => row.to_hash['Adj Close']
              )
            elsif last_market_date[:market_date] >= Date.parse(row.to_hash['Date'])
              break
            end
          else
            add_market_data = MarketData.new
            add_market_data.update_attributes(
              :market_date => row.to_hash['Date'],
              :ticker => symbol,
              :close_price => row.to_hash['Close'],
              :adj_close => row.to_hash['Adj Close']
            )
          end
        end
      end
    # else
    #   puts "NOT PULLING MARKET HISTORY"
    #end # end time check


    ###########################################################

    ## Collect Current Market Prices ##########################
    # ticker_string = ''
    # plus = '+'
    # @recent_data = []

    # tickers.each_with_index do |ticker, idx|
    #   ticker_string = ticker_string.concat(ticker.to_s)
    #   if idx < tickers.count-1
    #     ticker_string = ticker_string+plus
    #   end
    # end

    # url = "http://finance.yahoo.com/d/quotes.csv?s=#{ticker_string}&f=sd1t1l1"

    # CSV.new(open(url)).each_with_index do |line,idx|
    #   ticker = line[0]
    #   current = Hash.new
    #   current[:name] = line[0]
    #   current[:info] = {:trade_date => line[1], :trade_time => line[2], :trade_price => line[3]}
    #   @recent_data << current
    # end

  ###########################################################

    ## NAV CALC ###############################################
    # select only group transactions

    market_db = MarketData.order(:market_date)

    ##### EMPTY ARRAYS #####

    open_positions = []
    trades_array = []
    sells_log = []
    cash_changes = []

    transactions.each_with_index do |trade, idx|
      if trade[:action_type] == 'Buy' 

        # shovel transactions hash into trades_array
        trades_array << {:date => trade[:trade_date], :desc => 'BUY', :ticker => trade[:stock_symbol], :price => trade[:price], :qty => trade[:quantity], :commission => trade[:commission], :order => 1}

        # check if buy exists in open_positions array, if not add to array
        if open_positions.any? {|o| o[:ticker] == trade[:stock_symbol] && o[:price] == trade[:price] && o[:qty] > 0 && o[:date] == trade[:trade_date] && o[:mark] != true}
          matching_positions = open_positions.select {|o| o[:ticker] == trade[:stock_symbol] && o[:price] == trade[:price] && o[:mark] != true}
          last_index = (matching_positions.count) - 1
          matching_positions[last_index][:qty] += trade[:qty]
        else
          open_positions << {:date => trade[:trade_date], :ticker => trade[:stock_symbol], :price => trade[:price], :qty => trade[:quantity], :log => 'BUY', :commission => trade[:commission]}
          if open_positions.any? {|o| o[:ticker] == trade[:stock_symbol] && o[:price] == trade[:price] && o[:date] < trade[:trade_date]}
            matching_positions = open_positions.select {|o| o[:ticker] == trade[:stock_symbol] && o[:price] == trade[:price] && o[:date] < trade[:trade_date]}
            last_index = (matching_positions.count) - 1
            add_previous_qty = matching_positions[last_index][:qty]
            last_position = (open_positions.count) - 1
            open_positions[last_position][:qty] += add_previous_qty
          end
        end

      ###
      unique_prices = transactions.select {|o| o[:stock_symbol] == trade[:stock_symbol]}.uniq {|t| t[:price]}
      if unique_prices != nil
        unique_prices.each do |uq|
          check_positions = open_positions.select {|o| o[:ticker] == trade[:stock_symbol] && o[:price] == uq[:price]}
          check_pos_count = (check_positions.count) -1
          check_positions.each_with_index do |pos, idx|
            if idx < check_pos_count
              pos[:mark] = true
            end
          end
        end
      end
      ###
  ############################################################

    ############# SELL CHECK    
    elsif trade[:action_type] == 'Sell'

      if open_positions.any? {|o| o[:ticker] == trade[:stock_symbol] && o[:qty] > 0 && o[:mark] != true}
        ops = open_positions.select {|o| o[:ticker] == trade[:stock_symbol] && o[:qty] > 0 && o[:mark] != true}
        qty_sold = trade[:quantity] *-1
        ops.each do |op|
          if qty_sold > 0 && qty_sold >= op[:qty]
            remainder = qty_sold - op[:qty]
            op_decrease = qty_sold - remainder
            qty_subtracted = op[:qty] - op_decrease
            open_positions << {:date => trade[:trade_date], :ticker => trade[:stock_symbol], :price => op[:price], :qty => qty_subtracted, :sold => op_decrease, :log => 'SELL', :commission => trade[:commission]}
            sells_log << {:date => trade[:trade_date], :desc => 'SELL', :ticker => trade[:stock_symbol], :price => op[:price], :qty => op_decrease, :sell_price => trade[:price], :commission => trade[:commission], :order => 2}
            qty_sold = remainder
          elsif qty_sold > 0 && qty_sold < op[:qty]
            qty_subtracted = op[:qty] - qty_sold
            open_positions << {:date => trade[:trade_date], :ticker => trade[:stock_symbol], :price => op[:price], :qty => qty_subtracted, :sold => qty_sold, :sell_price => trade[:price], :commission => trade[:commission], :order => 2}
            break
          else
            puts "ERROR with qty_sold if: op: #{op} || Trade: #{trade} || Sold: #{qty_sold}"
          end
        end
      end

      ######
      unique_prices = transactions.select {|o| o[:stock_symbol] == trade[:stock_symbol]}.uniq {|t| t[:price]}
      if unique_prices != nil
        unique_prices.each do |uq|
          check_positions = open_positions.select {|o| o[:ticker] == trade[:stock_symbol] && o[:price] == uq[:price]}
          check_pos_count = check_positions.count - 1
          check_positions.each_with_index do |pos, idx|
            if idx < check_pos_count
              pos[:mark] = true
            end
          end
        end
      end
      #####

      ############################################################

      elsif trade[:action_type] == 'Credit Interest' || trade[:action_type] == 'Dividend'
          cash_changes << {:date => trade[:trade_date], :desc => trade[:action_type].upcase, :total => trade[:total_value], :order => 3}
      elsif trade[:action_type] == 'Cash Adjustment' || trade[:action_type] == 'Check'
          cash_changes << {:date => trade[:trade_date], :desc => 'WITHDRAWAL', :total => trade[:total_value], :order => 3}
      elsif trade[:action_type] == 'Journal'
          cash_changes << {:date => trade[:trade_date], :desc => 'DEPOSIT', :total => trade[:total_value], :order => 3}
      else
        puts 'ERROR: ACTION TYPE!'
        puts "error: #{trade[:action_type]}"
      end # if loop
    end # index each loop

    ################################
    ### Establish open position log
    op_log = []
    market_log = []

    op_buy_log = []
    op_buy = open_positions.select {|o| o[:log] == 'BUY'}
    op_buy.each do |op|
      op_buy_log << {:date => op[:date], :desc => 'POS', :ticker => op[:ticker], :price => op[:price], :qty => op[:qty], :commission => op[:commission]}
      op_log << {:date => op[:date], :ticker => op[:ticker], :price => op[:price], :qty => op[:qty], :commission => op[:commission]}
    end

    op_sell_log = []
    op_sell = open_positions.select {|o| o[:log] == 'SELL'}
    op_sell.each do |op|
      op_sell_log << {:date => op[:date], :desc => 'POS', :ticker => op[:ticker], :price => op[:price], :qty => op[:qty], :commission => op[:commission]}
      op_log << {:date => op[:date], :ticker => op[:ticker], :price => op[:price], :qty => op[:qty], :commission => op[:commission]}
    end

    ###############################

    op_log.each_with_index do |op, idx|
      if op[:qty] > 0
        start_date = op[:date]
        if op_log.any? {|o| o[:ticker] == op[:ticker] && o[:price] == op[:price] && o[:date] >= op[:date] && o[:qty] == 0 && o[:mark] != true}
          end_day = op_log.find {|o| o[:ticker] == op[:ticker] && o[:price] == op[:price] && o[:date] >= op[:date] && o[:qty] == 0 && o[:mark] != true}

app/views/static_pages/about.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="page-header">
        <h1>About</h1>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span8 offset2">
      <div class="hero-unit">
          <h2 class="featurette-heading">kurotrade. <span class="muted">the story.</span></h2><br />
          <p class="lead" style="text-align: justify;">kurotrade came out of the need to solve a problem. Mike started a General Partnership Investment Club with a few college buddies, it was thought of as a great way to get real experience trading and help diversify the risk by pooling smaller contributions together. After filling out a bunch of paperwork, CJSSW Investment Group was formed. The group was finally ready to start investing. However, only Mike had access to the account and the other partners often wanted updates to know what was going on.</p>
          <p class="lead" style="text-align: justify;">Mike felt his current job lacked real meaning - it was missing something. He decided to quit and join The Starter League and take the Web Development course. He went in wanting to solve a problem - create a platform where investment groups can easily monitor their stock portfolios. Mike plans to add future features to make kurotrade a powerful collaborative environment for investors.</p>
        </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span2 offset2">
      <%= image_tag '/assets/about_mike.jpg' %><br />
    </div>

    <div class="span6">
      <div class="hero-unit">
        <h2>Mike Chau</h2>
        <p class="lead" style="text-align: justify;">Mike graduated from Illinois Wesleyan University where he studied Finance and Risk Management. He is also part of The Starter League - Fall 2012 Cohort, he learned about Web Development with Ruby and Ruby on Rails framework.</p>
        <%= link_to image_tag('/assets/twitter.png'), 'https://twitter.com/money_mikec' %>
        <%= link_to image_tag('/assets/linkedin.png'), 'http://www.linkedin.com/pub/michael-chau/3a/902/727' %>
        <%= link_to image_tag('/assets/posterous.png'), 'http://mikechau.posterous.com/' %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="page-header">
        <h1>Talk to us!</h1>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span8 offset2">
      <div class="hero-unit">
        <h2>Questions? Comments? Suggestions?</h2><br />
        <div id="wufoo-z7x3p9"></div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var z7x3p9;(function(d, t) {
    var s = d.createElement(t), options = {
      'userName':'kurotrade', 
      'formHash':'z7x3p9', 
      'autoResize':true,
      'height':'437',
      'async':true,
      'header':'show'};
    s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
    s.onload = s.onreadystatechange = function() {
      var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
      try { z7x3p9 = new WufooForm();z7x3p9.initialize(options);z7x3p9.display(); } catch (e) {}};
    var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
  })(document, 'script');
</script>

app/views/static_pages/features.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="page-header">
        <h1>Features</h1>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span4 offset2">
      <div class="hero-unit">
        <h2>kurotrade supports:</h2>
        <ul>
          <li>Individual Portfolios</li>
          <li>Group Portfolios</li>
          <li>Manual Transactions</li>
          <li>CSV Uploading from Scottrade</li>
          <li>Net Asset Value</li>
        </ul><br />
        <h2>Future features:</h2>
        <ul>
          <li>One-Click CSV Uploading from Scottrade</li>
          <li>Group Collaboration tools</li>
          <li>Ownership Calculation</li>
        </ul>
      </div>
    </div>
    <div class="span4">
      <div class="hero-unit">
        <h2>Supported Brokers:</h2>
        <%= link_to image_tag('/assets/scottrade.png'), 'https://apply.scottrade.com/?refnum=USEN5849' %>
      </div>
    </div>
  </div>

</div>

app/views/static_pages/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide moveup">
  <div class="carousel-inner">
    <div class="item active">
      <img src="/assets/slide-01.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Welcome to kurotrade.</h1>
          <p class="lead">kurotrade is a flexible portfolio monitoring tool. Whether you are investing as an individual or as an investment group, you can conveniently keep track of your stock portfolio. </p>
          <%= link_to 'Register for closed beta', new_user_url, :class => "btn btn-large btn-primary" %> 
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/assets/slide-02.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Stock portfolio monitoring.</h1>
          <p class="lead">kurotrade makes stock portfolio monitoring incredibly easy. You simply upload your stock transactions and kurotrade will calculate your daily net asset value. If you're in an investment group you and your partners can each have an account and access the same portfolio dashboard.</p>
          <%= link_to 'Demo', dashboard_url, :class => 'btn btn-large btn-primary' %>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/assets/slide-03.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>We're just getting started.</h1>
          <p class="lead">More planned features are on the way. We currently support manual transaction entry and Scottrade brokerage transactions via CSV file upload.</p>
          <%= link_to 'Learn more', features_url, :class => 'btn btn-large btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <!-- Three columns of text below the carousel -->

<div class="container-fluid marketing">

  <div class="row-fluid">
    <div class="span4">
      <i class="icon-group" style="font-size: 150px; line-height: 150px; margin-bottom: -25px;"></i>
      <h2>Create a Group</h2>
      <p>Are you part of an investment group and finding it difficult for keeping all the partners updated with the portfolio? With kurotrade, you can create a group portfolio where each partner has their own account.</p>
<!--       <p><a class="btn" href="#">View details &raquo;</a></p> -->
    </div><!-- /.span4 -->
    <div class="span4">
      <i class="icon-upload" style="font-size: 150px; line-height: 150px; margin-bottom: -25px;"></i>
      <h2>Upload Transactions</h2>
      <p>kurotrade supports CSV files from Scottrade and can automatically parse through your trades, manual transaction adding is also supported.</p>
<!--       <p><a class="btn" href="#">View details &raquo;</a></p> -->
    </div><!-- /.span4 -->
    <div class="span4">
      <i class="icon-bar-chart" style="font-size: 150px; line-height: 150px; margin-bottom: -25px"></i>
      <h2>Monitior Portfolio</h2>
      <p>After your transactions have been created or uploaded, you can now monitor your portfolio, kurotrade calculates your net asset value.</p>
<!--       <p><a class="btn" href="#">View details &raquo;</a></p> -->
    </div><!-- /.span4 -->
  </div><!-- /.row -->
</div>

app/views/static_pages/mock_dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="span8">
      <h1>Portfolio Dashboard</h1>
    </div>

    <div class="span4">
      <h1 class="date"><%= Date.today.strftime("%b %e, %Y") %></h1>
    </div>
  </div>

  <div class="row"><!-- chart row-->
    <div class="span12">
      <div id="chart1">
        <svg></svg>
      </div>
    <div>
  </div> <!-- /chart row -->

  <hr />

  <div class="row"><!-- metrics row -->

    <div class="span5"> <!-- start: span 5 -->
      <h3>Open Positions</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Ticker</th>
            <th>Book</th>
            <th>Market</th>
            <th>Qty</th>
            <th>Change</th>
            <th>Return</th>
          </tr>
        </thead>
        <tbody>
          <% @display_op.each do |op| %>
            <% market_price = op[:market][0][:trade_price] %>
            <% market_total = market_price*op[:qty] %>
            <% change = market_total - op[:book_value] %>
            <% stock_return = ((change) / op[:book_value]) * 100 %>
          <tr>
            <td><%= op[:ticker] %></td>
            <td>$<%= op[:price] %></td>
            <td>$<%= market_price %></td>
            <td><%= op[:qty] %></td>
            <td><%= number_to_currency(change) %></td>
            <td><%= number_to_percentage(stock_return) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div><!-- end: span 5 -->

    <div class="span4"><!-- start: span 4 (2)-->
      <h3>Vitals</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Category</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Cash Balance</td>
            <td><%= number_to_currency(@cash_balance) %></td>
          </tr>
          <tr>
            <td>Stock Balance</td>
            <td><%= number_to_currency(@stock_balance) %></td>
          </tr>
          <tr>
            <td>Net Asset Value</td>
            <td><%= number_to_currency(@net_asset_value) %></td> 
          </tr>
          <tr>
            <td>NAV Units</td>
            <td><%= number_with_precision(@nav_units, :precision => 2, :delimiter => ',') %></td>
          </tr>
          <tr>
            <td>NAV Per Unit</td>
            <td><%= number_to_currency(@nav_per_unit) %></td>
          </tr>
        </tbody>
      </table>
    </div><!-- end: span 4 (2) -->
    <div class="span3"> <!-- start: span 3 -->
      <h3>Net Asset Value %</h3>
      <% if @return_nav > 0 %>
        <div class="square_green">
      <% else %>
        <div class="square_red">
      <% end %>
          <h1 class= "nav_stat"><%= number_to_percentage(@return_nav, :precision => 2) %></h1>
        </div>
    </div><!-- end: span 3 -->
  </div><!-- /metrics row -->

</div> <!-- /container -->

<!-- javascripts -->
<script>
var testdata = [
    { 
      "key" : "Net Asset Value" , 
      "bar": true,
      "values" : [
        <% @portfolio.each_with_index do |p, idx| %>
          <% if idx != @portfolio.count-1 %> 
            [ <%= p[:date] %>, <%= p[:nav] %> ],
          <% else %>
            [ <%= p[:date] %>, <%= p[:nav] %> ]
          <% end %>
        <% end %>
      ]
    } , 

    { 
      "key" : "NAV Return" , 
      "values" : [ 
        <% @portfolio.each_with_index do |p, idx| %>
          <% if idx != @portfolio.count-1 %> 
            [ <%= p[:date] %>, <%= p[:return] %> ],
          <% else %>
            [ <%= p[:date] %>, <%= p[:return] %> ]
          <% end %>
        <% end %>
      ]
    }
].map(function(series) {
  series.values = series.values.map(function(d) { return {x: d[0], y: d[1] } });
  return series;
});

nv.addGraph(function() {
    var chart = nv.models.linePlusBarWithFocusChart()
        .margin({top: 30, right: 60, bottom: 50, left: 70})
        .x(function(d,i) { return i })
        .color(d3.scale.category10().range());

    chart.xAxis.tickFormat(function(d) {
      var dx = testdata[0].values[d] && testdata[0].values[d].x || 0;
      if (dx > 0) {
          return d3.time.format('%x')(new Date(dx))
      }
      return null;
    });

    chart.x2Axis.tickFormat(function(d) {
      var dx = testdata[0].values[d] && testdata[0].values[d].x || 0;
      return d3.time.format('%x')(new Date(dx))
    });
    
    chart.y1Axis
        .tickFormat(function(d) { return '$' + d3.format(',f')(d)});

    chart.y3Axis
        .tickFormat(function(d) { return '$' + d3.format(',f')(d)});

    chart.y2Axis
        .tickFormat(function(d) { return d3.format(',.2f')(d) + '%' });

    chart.y4Axis
        .tickFormat(function(d) { return d3.format(',.2f')(d) + '%' });
        
    chart.bars.forceY([0]);
    chart.bars2.forceY([0]);
    //chart.lines.forceY([0]);

    d3.select('#chart1 svg')
        .datum(testdata)
      .transition().duration(500).call(chart);

    nv.utils.windowResize(chart.update);

    return chart;
});

</script>

app/views/static_pages/testing.html.erb
<h1> KUROTRADE </h1>

<hr />

<h2> TEMP ADMIN PANEL </h2>

<ul>
  <li>
    USERS: <%= link_to "Index", users_url %> | <%= link_to "Create", new_user_url %>
  </li>

  <li>
    GROUPS: <%= link_to "Index", groups_url %> | <%= link_to "Create", new_group_url %>
  </li>

  <li>
    PORTFOLIOS: <%= link_to "Index", portfolios_url %> | <%= link_to "Create", new_portfolio_url %>
  </li>

  <li>
    TRANSACTIONS: <%= link_to "Index", transactions_url %> | <%= link_to "Create", new_transaction_url %>
  </li>
</ul>

app/views/static_pages/thanks.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="page-header">
        <h1>Thanks for Signing Up!</h1>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span8 offset2">
      <div class="hero-unit">
        <h2>kurotrade will be entering beta soon.</h2>
        <p class="lead">We will be contacting users shortly, thank you for your patience and interest!</p>
        <div class="row">
          <div class="span5 offset1">
            <a href="https://twitter.com/kurotrade" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @kurotrade</a><a href="https://twitter.com/intent/tweet?text=I%20signed%20up%20for%20beta!%20%40kurotrade%20 - stock portfolio monitoring for groups!" class="twitter-mention-button pull-right" data-size="large" data-related="kurotrade">Tweet to @kurotrade</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>