config/routes.rb
Kurotrade::Application.routes.draw do

  root :to => 'static_pages#index'

  #resource :session, :only => [:new, :create, :destroy]

  get "login" => 'sessions#new', as: :login
  post "session" => 'sessions#create' 
  get "logout" => 'sessions#destroy', as: :logout

  #get '/balances', :to => 'static_pages#balance_exp'
  match '/boarding/welcome', :to => 'static_pages#welcome', as: :welcome
  match '/boarding/partner', :to => 'static_pages#new_partner', as: :boarding_partner
  match '/boarding/individual', :to => 'static_pages#new_individual', as: :boarding_individual

  get '/dashboard', :to => 'static_pages#mock_dashboard', as: :dashboard
  get '/about', :to => 'static_pages#about', as: :about
  get '/contact', :to => 'static_pages#contact', as: :contact

  resources :transactions, :to => 'static_pages#index'
  match '/transactions/file_upload', :to => 'transactions#scottrade_csv_parser', :as => 'transactions_upload'

  resources :portfolios, :to => 'static_pages#index'

  resources :groups, :to => 'static_pages#index'
  match '/individual/new', :to => 'groups#new', :as => 'new_individual'

  resources :beta_users

  match '/users/new', :to => 'beta_users#new', :as => 'new_user'
  match '/beta', :to => 'beta_users#new', :as => 'new_user'
  get '/thanks', :to => 'static_pages#thanks', as: :thanks
  get '/features', :to => 'static_pages#features', as: :features
  resources :users
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name

  has_many :portfolios
  has_many :transactions
  has_many(:users, { :through => :portfolios })
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, :html => { :class => "form-horizontal"} ) do |f| %>
  <% if @group.errors.any? %>
    <div id="alert alert-error">
      <h2>There are <%= pluralize(@group.errors.count, "error") %> errors:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li style="color: #B94A48; font-weight: bold;"><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <hr />
  <% end %>

  <fieldset>
    <div class="control-group">
        <%= f.text_field :name, :style => "width: 100%", :placeholder => "name" %>
    </div>
    <div class="control-group">
      <%= f.submit "Submit", :class => "btn btn-large btn-primary pull-right" %>
    </div>
  </fieldset>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>