config/routes.rb
Kurotrade::Application.routes.draw do

  root :to => 'static_pages#index'

  #resource :session, :only => [:new, :create, :destroy]

  get "login" => 'sessions#new', as: :login
  post "session" => 'sessions#create' 
  get "logout" => 'sessions#destroy', as: :logout

  #get '/balances', :to => 'static_pages#balance_exp'
  match '/boarding/welcome', :to => 'static_pages#welcome', as: :welcome
  match '/boarding/partner', :to => 'static_pages#new_partner', as: :boarding_partner
  match '/boarding/individual', :to => 'static_pages#new_individual', as: :boarding_individual

  get '/dashboard', :to => 'static_pages#mock_dashboard', as: :dashboard
  get '/about', :to => 'static_pages#about', as: :about
  get '/contact', :to => 'static_pages#contact', as: :contact

  resources :transactions, :to => 'static_pages#index'
  match '/transactions/file_upload', :to => 'transactions#scottrade_csv_parser', :as => 'transactions_upload'

  resources :portfolios, :to => 'static_pages#index'

  resources :groups, :to => 'static_pages#index'
  match '/individual/new', :to => 'groups#new', :as => 'new_individual'

  resources :beta_users

  match '/users/new', :to => 'beta_users#new', :as => 'new_user'
  match '/beta', :to => 'beta_users#new', :as => 'new_user'
  get '/thanks', :to => 'static_pages#thanks', as: :thanks
  get '/features', :to => 'static_pages#features', as: :features
  resources :users
  
end

app/controllers/transactions_controller.rb
require 'csv'
require 'date'
require 'open-uri'

class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.order(:trade_date)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end


# def convert_to_date(str)
#   # 1/12/2012 - initial
#   # 2012/12/1 - conversion
#   if str != nil
#     date_array = str.split("/")
#     converted_date = Date.parse(("#{date_array[2]}/#{date_array[0]}/#{date_array[1]}").to_s)
#     return converted_date
#   else
#     return 'N/A'
#   end
# end

  #CSV PARSING
  def scottrade_csv_parser #start_1
    if request.post? && params[:file].present? #start_2
      infile = params[:file].tempfile

      Transaction.delete_all #delete only group id

      CSV.foreach(infile, :headers => true, :col_sep => ';') do |row| #start_3

        txn = Transaction.new

        #binding.pry

        if row.to_hash["Symbol"] != nil || row.to_hash["Quantity"] != nil || row.to_hash["Price"] != nil || row.to_hash["ActionNameUS"] || row.to_hash["TradeDate"] != nil || row.to_hash["SettledDate"] != nil || row.to_hash["Interest"] != nil || row.to_hash["Amount"] != nil || row.to_hash["Commission"] != nil || row.to_hash["Fees"] != nil || row.to_hash["CUISP"] != nil || row.to_hash["Description"] != nil || row.to_hash["ActionId"] != nil || row.to_hash["TradeNumber"] != nil || row.to_hash["RecordType"] != nil #start_4
            
            txn.update_attributes(
              :stock_symbol => row.to_hash["Symbol"], #Row 1
              :quantity => row.to_hash["Quantity"], #Row 2
              :price => row.to_hash["Price"], #Row 3
              :action_type => row.to_hash["ActionNameUS"], #Row 4
              :trade_date => Transaction.convert_to_date(row.to_hash["TradeDate"]),
              :settle_date => Transaction.convert_to_date(row.to_hash["SettledDate"]), #Row 6
              :interest => row.to_hash["Interest"], #Row 7
              :total_value => row.to_hash["Amount"].gsub(",", ""), #Row 8
              :commission => row.to_hash["Commission"], #Row 9
              :fees => row.to_hash["Fees"], #Row 10
              :cusip => row.to_hash["CUISP"], #Row 11
              :description => row.to_hash["Description"], #Row 12
              :action_id => row.to_hash["ActionId"], #Row 13
              :trade_id => row.to_hash["TradeNumber"], #Row 14
              :record_type => row.to_hash["RecordType"], #Row 15
              :broker => "Scottrade", #Manual / Future Drop Down menu?
              :input_method => "CSV", #2 options CSV or MANUAL
              :group_id => "1", #a test, set by page->cookie?
              :user_id => session[:user_id] #a test, set by user.id->cookie?
            )
        end #end_4

        #mechanize
        #Transaction

      end #end_3
      redirect_to transactions_url
    else
      redirect_to new_transaction_url, notice: 'Error: Select a File!'
    end #end_2

    #*** Some sort of validation to make sure Transaction is updated
  end #end_1

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :trade_id %><br />
    <%= f.text_field :trade_id %>
  </div>
  <div class="field">
    <%= f.label :stock_symbol %><br />
    <%= f.text_field :stock_symbol %>
  </div>
  <div class="field">
    <%= f.label :trade_date %><br />
    <%= f.date_select :trade_date %>
  </div>
  <div class="field">
    <%= f.label :settle_date %><br />
    <%= f.date_select :settle_date %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :commission %><br />
    <%= f.text_field :commission %>
  </div>
  <div class="field">
    <%= f.label :fees %><br />
    <%= f.text_field :fees %>
  </div>
  <div class="field">
    <%= f.label :interest %><br />
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :total_value %><br />
    <%= f.text_field :total_value %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :broker %><br />
    <%= f.text_field :broker %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_upload.html.erb
<%= form_tag transactions_upload_url, :multipart => true do %>
  <%= label_tag :file %> 
  <%= file_field_tag :file %>
  <%= submit_tag %>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Group</th>
    <th>User ID</th>
    <th>Trade</th>
    <th>Stock symbol</th>
    <th>Trade date</th>
    <th>Settle date</th>
    <th>Shares</th>
    <th>Price</th>
    <th>Commission</th>
    <th>Fees</th>
    <th>Interest</th>
    <th>Total value</th>
    <th>Description</th>
    <th>Broker</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.group_id %></td>
    <td><%= transaction.user_id %></td>
    <td><%= transaction.trade_id %></td>
    <td><%= transaction.stock_symbol %></td>
    <td><%= transaction.trade_date %></td>
    <td><%= transaction.settle_date %></td>
    <td><%= transaction.quantity %></td>
    <td><%= transaction.price %></td>
    <td><%= transaction.commission %></td>
    <td><%= transaction.fees %></td>
    <td><%= transaction.interest %></td>
    <td><%= number_with_delimiter(transaction.total_value, :precision => 2, :delimiter => ',') %></td>
    <td><%= transaction.description %></td>
    <td><%= transaction.broker %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>
<hr />
<%= notice %>
<h2>Create a Transaction</h2>
<%= render 'form' %>

<hr />
<h2>Upload a CSV</h2>
<%= render 'upload' %>

<hr />

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @transaction.group_id %>
</p>

<p>
  <b>Trade:</b>
  <%= @transaction.trade_id %>
</p>

<p>
  <b>Stock symbol:</b>
  <%= @transaction.stock_symbol %>
</p>

<p>
  <b>Trade date:</b>
  <%= @transaction.trade_date %>
</p>

<p>
  <b>Settle date:</b>
  <%= @transaction.settle_date %>
</p>

<p>
  <b>Quantity:</b>
  <%= @transaction.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @transaction.price %>
</p>

<p>
  <b>Commission:</b>
  <%= @transaction.commission %>
</p>

<p>
  <b>Fees:</b>
  <%= @transaction.fees %>
</p>

<p>
  <b>Interest:</b>
  <%= @transaction.interest %>
</p>

<p>
  <b>Total value:</b>
  <%= @transaction.total_value %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>Broker:</b>
  <%= @transaction.broker %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>