config/routes.rb
Kurotrade::Application.routes.draw do

  root :to => 'static_pages#index'

  #resource :session, :only => [:new, :create, :destroy]

  get "login" => 'sessions#new', as: :login
  post "session" => 'sessions#create' 
  get "logout" => 'sessions#destroy', as: :logout

  #get '/balances', :to => 'static_pages#balance_exp'
  match '/boarding/welcome', :to => 'static_pages#welcome', as: :welcome
  match '/boarding/partner', :to => 'static_pages#new_partner', as: :boarding_partner
  match '/boarding/individual', :to => 'static_pages#new_individual', as: :boarding_individual

  get '/dashboard', :to => 'static_pages#mock_dashboard', as: :dashboard
  get '/about', :to => 'static_pages#about', as: :about
  get '/contact', :to => 'static_pages#contact', as: :contact

  resources :transactions, :to => 'static_pages#index'
  match '/transactions/file_upload', :to => 'transactions#scottrade_csv_parser', :as => 'transactions_upload'

  resources :portfolios, :to => 'static_pages#index'

  resources :groups, :to => 'static_pages#index'
  match '/individual/new', :to => 'groups#new', :as => 'new_individual'

  resources :beta_users

  match '/users/new', :to => 'beta_users#new', :as => 'new_user'
  match '/beta', :to => 'beta_users#new', :as => 'new_user'
  get '/thanks', :to => 'static_pages#thanks', as: :thanks
  get '/features', :to => 'static_pages#features', as: :features
  resources :users
  
end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>kurotrade</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'kurotrade', root_url, :class => 'brand' %>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <% if current_user %>
              <li><%= link_to 'Dashboard', dashboard_url %></li>
              <li><%= link_to 'Transactions', transactions_url %></li>
              <li><%= link_to 'Portfolios', portfolios_url %></li>
              <li><%= link_to 'Groups', groups_url %></li>
            <% else %>
              <li><%= link_to 'Home', root_url %></li>
              <li><%= link_to 'Demo', dashboard_url %></li>
              <li><%= link_to 'Features', features_url %></li>
            <% end %>
              <li><%= link_to 'About', about_url %></li>
              <li><%= link_to 'Contact', contact_url %></li>
          </ul>
          <ul class="nav pull-right">
            <% if current_user %>
              <li><%= link_to 'Settings', edit_user_url(current_user.id) %></li>
              <li><%= link_to 'Logout', logout_url %></li>
            <% else %>
              <li><%= link_to 'Register', new_user_url %></li>
              <li><%= link_to 'Login', login_url %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

<%= render 'layouts/flash_messages' %>

<%= yield %>

<script>
  var url = window.location;
  // Will only work if string in href matches with location
  $('ul.nav a[href="'+ url +'"]').parent().addClass('active');

  // Will also work for relative and absolute hrefs
  $('ul.nav a').filter(function() {
      return this.href == url;
  }).parent().addClass('active');
</script>

</body>
</html>